### ISSUE TITLE
Pool Metadata and stakeDistribution

### ISSUE THREAD

**Issue by tapiocapool** [KtorZ/cardano-ogmios#18]
Hello again guys, I'm traversing the Shelley Era using RequestNext but up to now I can't find any information about pools metadata. For example, from the cardano-cli if I query the ledger-state, it spits a huge json file where at some point I find info about pool metadata URL and stuff. Maybe I'm doing something wrong, or maybe I'm looking in the wrong place.

Ps: a stakeDistribution query at this point slot: 6984000 hash: 7259bafc5518510796ed11d62140d305e113bcb2f4294fb6f194b3e108efb2e4
doesn't give any feedback, no error, no success, it is ok?

Thanks!

@KtorZ Thanks for the tips on FP

**Comment by rhyslbw** [comment]
Should be in `Certificate.poolRegistration`

https://github.com/KtorZ/cardano-ogmios/blob/8a7c44c1e8cddcb645e7070f2a79070bba53a8b9/docs/static/ogmios.wsp.json#L1826-L1842

**Comment by tapiocapool** [comment]
Thank you so much! I was missing out a lot of info because I wasn't digging enough in the block structure but thanks to your instructions I could find where was the info located.

Ps: Forget about the stakeDistribution issue, it was my fault on the query timing.

You can close the ticket if you want

**Comment by KtorZ** [comment]
@tapiocapool what you're looking at in the cardano-cli is the output of a debug query which outputs the entire ledger state. That query is not meant to be used by production system, and that's why it is not available in Ogmios. 

Unfortunately, there's no standard query which will give you this bit of information. The currently "correct" way of retrieving this would be as @rhyslbw pointed out, by looking at pools' registration certificate in transactions using the [local chain sync](https://ktorz.github.io/cardano-ogmios/mini-protocols/local-chain-sync/) protocol and crawling the chain block by block. 

---

Having said that, I am quite interested about what you mentioned above: 

>  doesn't give any feedback, no error, no success, it is ok?

Even if you make a query outside of a compatible era (e.g. make a Shelley query in the Byron era), you _should_ get a reply from the server.  Can you describe a bit more what you did? I assume you tried to acquire the point at slot 6984000 and then run the query :thinking: ?

**Comment by tapiocapool** [comment]
Thanks guys!!! I don't mind crawling the whole blockchain, if that's the way, that's the way, is good to know this instead of wondering about if there was a better way or if I'm doing all wrong.

> Even if you make a query outside of a compatible era (e.g. make a Shelley query in the Byron era), you should get a reply from the server. Can you describe a bit more what you did? I assume you tried to acquire the point at slot 6984000 and then run the query thinking ?

I made a mistake in my JS code so the function was calling the Query out of sync, I mean almost on the exit point of the program, so it was impossible that I could read the answer. Oh by the way, I forgot to tell you that I'm working on the testnet, not the mainnet. My bad.

**Comment by KtorZ** [comment]
@tapiocapool thanks for your feedback. I'll now close this ticket, feel free to reach out if you've questions. I may start building a FAQ :thinking:
