### ISSUE TITLE
fault definitions missing from JSON-WSP schema

### ISSUE THREAD

**Issue by rhyslbw** [KtorZ/cardano-ogmios#20]
#### What Git revision are you using? 
`b3eb7596661be2a5d013a321f0dc8fbec781d492`
#### What operating system are you using, and which version?

- [x] Linux / Ubuntu

#### Describe what the problem is? 
The following response was returned when calling an unknown query:
```
 {
      version: '1.0',
      fault: { string: 'Invalid request: invalid query.', code: 'client' },
      servicename: 'ogmios',
      type: 'jsonwsp/fault'
    }
```
...  however there is no definition in the schema and therefore unexpected.

#### What should be the expected behavior?
Faults definitions in the schema, as per https://handwiki.org/wiki/JSON-WSP

**Comment by KtorZ** [comment]
I am not 100% positive about how to handle /document that one. In principle, faults only occurs when clients submit invalid queries; that can occur pretty much in any request and the behavior is specified by the WSP specification.

However, it could be indeed document as a top-level definition in the json-schema, since the different type of client faults are known already and could be listed. Is this what you're suggesting?

**Comment by rhyslbw** [comment]
> Is this what you're suggesting?

Yes. It means the possible response is then included in any generated code that uses the JSON-WSP schema as a source.

**Comment by KtorZ** [comment]
Now documented as a top-level definition in the schema (`Fault`): https://github.com/KtorZ/cardano-ogmios/commit/4fcb0437d7935d71a8c9c1cdf2c75af21a5c5e02
