### ISSUE TITLE
Installation error following instructions

### ISSUE THREAD

**Issue by nicarq** [KtorZ/cardano-ogmios#22]
If I follow the instructions from https://ogmios.dev/getting-started/docker/
(https://github.com/KtorZ/cardano-ogmios/blob/557c5d790e12bfd0875af77d14c3d9537a5858d1/docs/content/getting-started/docker.md) and do for example:

```
NETWORK=mainnet docker-compose --project-name cardano-ogmios-mainnet up
```

I get the following error

```
ERROR: build path /xxx/xxx/ogmios/server either does not exist, is not accessible, or is not a valid URL.
```

When I was reading the documentation I got the idea that I just could install it using Docker, but I still need the source code. If I get a copy of the repo using `git clone --recursive ...` and then I use the previous command everything seems to work fine.

Suggestion: clarify that the source code is still required when using Docker.

**Comment by KtorZ** [comment]
Thanks for reporting! This fails because of the `build` clause in the compose specification; I guess docker is trying to lookup path even though it should by default used the specified image. 

I've adjusted the documentation in consequence to require a `git clone` and provide working instructions:

https://ogmios.dev/getting-started/docker/
