### ISSUE TITLE
Is the block timestamp and transaction timestamps are not part of the block?

### ISSUE THREAD

**Issue by ashisherc** [KtorZ/cardano-ogmios#3]
I was looking for block and transaction timestamp, but couldn't find them inside the block.

**Comment by ashisherc** [comment]
Is the slot considered the date-time? Currently, it is the 20s duration, so the block and all trxs in a slot will have the same timestamp?

**Comment by KtorZ** [comment]
> so the block and all trxs in a slot 

Indeed. There's no "precise" timestamp because from the network perspective, it doesn't make sense. The network temporality is divided in slots and there's the smallest granularity is the slot length. This is why blocks (and therefore transactions) are only timestamped with a slot number. 

A software which want to show a corresponding UTC timestamp would need:

a) To know the blockchain start time (this is part of the genesis data, e.g. `1506203091` as a POSIX time for mainnet). 

b) To know the slot duration for each epoch (on Byron, it's unlikely to change and has always been equal to 20s, but this can in practice change arbitrarily through protocol updates. More likely to happen in Shelley). 

c) Arbitrarily pick a moment in the slot as a reference for UTC time. Could be the beginning of the slot, the middle, the end or anywhere that you think would make sense. For the record, `cardano-wallet` uses the beginning of the slot because it makes calculation a bit easier and it prevents transactions to be timestamped "in the future" if submitted early in the slot :)

**Comment by ashisherc** [comment]
Thanks for the detailed response. It makes sense. 👍

**Comment by KtorZ** [comment]
@Hathoriel would something like https://github.com/CardanoSolutions/ogmios/issues/165 be interesting for you?

**Comment by Hathoriel** [comment]
I will check that, thanks!

**Comment by Hathoriel** [comment]
It is only issue. With the #165 will I be able to get UTC (relative or absolute) timestamp of the transaction?

**Comment by KtorZ** [comment]
With #165 , you'll be able to get a UTC timestamp of any slot. So, consequently, since transactions are parts of blocks which are assigned to slot, then yes.

**Comment by Hathoriel** [comment]
One slot can have multiple blocks inside?

**Comment by Hathoriel** [comment]
Yes I am interested for it👍

**Comment by Hathoriel** [comment]
@KtorZ But if I do the following calculation example:

I take the blockchain start time of mainnet which you have posted: 
**1506203091**
I take the following transaction https://explorer.cardano.org/en/block?id=1dfedcae3e3f8310d0891041e73dd3bd1d92ceee670d76c9ebcc5cc8b0a5ab37 which has slot **62670548**.
And finally, the slot time is **20** seconds. 

Based on this:
62670548 * 20 = 1253410960
And 1253410960 + 1506203091 = 2759614051

![image](https://user-images.githubusercontent.com/10884869/171801006-8b4d9d2c-e1fd-47bc-99f0-3864f67a7918.png)

Which **Tuesday, 12 June 2057 23:27:31** doesn't make sense. Could you please comment on my calculation?

**Comment by KtorZ** [comment]
The slot time is actually 20 seconds only during the Byron era, and 1 second since the Shelley era (which started at slot `4492800` on mainnet, and slot `1598400` on testnet).

**Comment by KtorZ** [comment]
By the way, there's a query in Ogmios' [state-query protocol](https://ogmios.dev/mini-protocols/local-state-query/): `eraSummaries` that gives you the exact epoch boundaries (in slot, epoch and utc) of each era of the network with the relevant parameters for each, to do slot arithmetic.

**Comment by Hathoriel** [comment]
> The slot time is actually 20 seconds only during the Byron era, and 1 second since the Shelley era (which started at slot `4492800` on mainnet, and slot `1598400` on testnet).

And am I able to get a slot time for every era? It is somewhere written it?
