### ISSUE TITLE
What is the oldest point, that can be aquired?

### ISSUE THREAD

**Issue by MarcelKlammer** [KtorZ/cardano-ogmios#42]
The initial reason I started looking into cardano-ogmios was the retrieval of stake distribution at the last epoch boundary, since that isn't available in cardano-db-sync.

I now tried to aquire the last block of mainnet epoch 263, but it fails with pointTooOld.

So what's the max delta, that we can inspect/query?

**Comment by MarcelKlammer** [comment]
Something is odd here. I acquire a point in the not too distance past (a hew hours). Query the stake distribution and get the below result for my mainnet pool.

```
 AcquireSuccess: {
      point: {
        slot: 28705041,
        hash: '5a4d13fd2716867cb0d6d389ff907a1dca6ac507fbc7fbc75e5876906a7d0be4'
      }
    }

pool1qqqqpanw9zc0rzh0yp247nzf2s35uvnsm7aaesfl2nnejaev0uc: {
  stake: '4451022567618/4648873639099193',
  vrf: 'bb862fcc397de6c06dea9a9ad8442a3d17826e01799a79b861fc083341eaed3d'
}
```

If I don't aquire:

```
pool1qqqqpanw9zc0rzh0yp247nzf2s35uvnsm7aaesfl2nnejaev0uc: {
  stake: '31086662114967/32542115473694351',
  vrf: 'bb862fcc397de6c06dea9a9ad8442a3d17826e01799a79b861fc083341eaed3d'
}

32542115473694351 vs
4648873639099193

```

Where 4648873639099193 is the current treasury amount.

**Comment by KtorZ** [comment]
The ledger has a "memory" of the past of about ~3k blocks if I recall correctly where k=2160 on mainnet. That is about ~6480 blocks, so ~36h in the past on mainnet from the network tip.

**Comment by KtorZ** [comment]
Note that the retrieval of stake distribution for past epochs is not something that is generally possible in Cardano. In order to do this, you would need to be able to run the actual ledger and "pause it" at each epoch to calculate this information. The ledger itself doesn't keep any form of history or more generally, it doesn't keep anything that isn't strictly necessary. The ledger doesn't even have an history of all past transactions; instead it maintain a UTxO set which is always evolving: old UTxOs are purged and only the current set is maintained.

**Comment by MarcelKlammer** [comment]
Then the results make more sense. So we would actually need some kind of db-sync addon, that can rewind tx until last block of last epoch to get the utxo set of that slot. So I will leave that out for now. Thanks for clarifying.

**Comment by KtorZ** [comment]
> that can rewind tx until last block of last epoch to get the utxo set of that slot

That is relatively easy to achieve using the chain-sync mini-protocol. But it won't help you w.r.t to the stake distribution. The stake distribution is not only calculated from the UTxO, but also from rewards and some other factors that aren't part of the UTxO...

**Comment by vlall** [comment]
Hi, I'm posting this question here, since it's relevant to the current discussion. After reading through the issues, running the code, and using Ogmios, I'm wondering, is there a way to build an add-on to Ogmios in its current state and sync it up to write blockchain data into a database similar to what db-sync does? This could be useful for developers looking to customize the information we sync into the database, as well as sync to different database types (NoSQL), and remove some overhead for more advanced users.

I recognize a few hurdles as already mentioned in this issue and others:
> The ledger has a "memory" of the past of about ~3k blocks if I recall correctly where k=2160 on mainnet. That is about ~6480 blocks, so ~36h in the past on mainnet from the network tip.

> you would need to be able to run the actual ledger and "pause it" at each epoch to calculate this information.

> [Obtaining timestamps](https://github.com/KtorZ/cardano-ogmios/issues/3)

However, I just wanted to know if this seems like a feasible idea. Thank you!

**Comment by MarcelKlammer** [comment]
cncli does exactly that.

It writes all blocks into a local db and helps SPOs to calculate the leader events.

So it should be achievable.

**Comment by KtorZ** [comment]
@vlall that is totally doable. You could actually reimplement most of db-sync using ogmios.

Ogmios really is an interface of the node; but translated to Json + Websocket.

**Comment by vlall** [comment]
> cncli does exactly that.
@MarcelKlammer which tool is cncli?

> @vlall that is totally doable. You could actually reimplement most of db-sync using ogmios.
Perfect thanks! Yes, one concern was how i'd get the full snapshot of the blockchain, but i believe you explained this with the stopping/pausing of the sync. In this case, i'd probably need to run the node separately and pause in-between to make requests in Ogmios. Then I can infer the time stamps like you've explained earlier using the slot numbers and genesis time stamp.

**Comment by MarcelKlammer** [comment]
https://github.com/AndrewWestberg/cncli
